#! /bin/bash

# Only run as root
if [ $(id -u) -ne 0 ]; then
    echo "Snapshots must be created as root"
    exit -1
fi

declare -A SUBVOLUMES
SRC_SNAPSHOTS=/root/btrfs_snapshots
DEST_SNAPSHOTS=/root/sd_snapshots
SUBVOLUMES=(['/']='root' ['/root']='root_home' ['/home']='home')
NAME=$(date -I)

mount $SRC_SNAPSHOTS
mount $DEST_SNAPSHOTS

for target in ${!SUBVOLUMES[@]}; do
    target_src=$SRC_SNAPSHOTS/${SUBVOLUMES[$target]}
    target_dest=$DEST_SNAPSHOTS/${SUBVOLUMES[$target]}

    btrfs subvolume snapshot -r $target $target_src/$NAME
    sync

    # Get the list of snapshots
    list=($(ls $target_src))

    # Determine if incremental send is used
    if [ ${#list[@]} -ge 2 ]; then
        echo "Previous snapshot of $target is at $target_src/${list[-2]}"
        btrfs send -p $target_src/${list[-2]} $target_src/${list[-1]} | btrfs receive $target_dest
        sync
    else
        echo "No previous snapshot to use as base"
        btrfs send $target_src/${list[-1]} | btrfs receive $target_dest
        sync
    fi
done

umount $SRC_SNAPSHOTS
umount $DEST_SNAPSHOTS
